# -*- coding: utf-8 -*-
"""Assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZepwXIoKZikREqu8mGa_RMH4-QzLmTRk

# Basic Python

## 1. Split this string
"""

s = "Hi there Sam!"

x=s.split()

"""## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.
"""

planet = "Earth"
diameter = 12742

txt="The diameter of {planet} is {diameter} kilometers".format(planet="Earth", diameter=12742)

"""## 3. In this nest dictionary grab the word "hello"
"""

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

print(d['k1'][3]['tricky'][3]['target'][3])

"""# Numpy"""

import numpy as np

"""## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?
"""

array = np.zeros(10)*5
print("The array of 10 Zeros are:")
print(array)

array= np.zeros(10)
print("The array of 10 Fives are:")
print(array)

"""## 5. Create an array of all the even integers from 20 to 35"""

array=np.arange(21,34,4)
print("Array of all the even integers from 21 to 34 are:")
print(array)

"""## 6. Create a 3x3 matrix with values ranging from 0 to 8"""

x= np.arange(0,9).reshape(3,3)
print(x)



"""## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])
"""

a= np.array([1,2,3])
b= np.array([4,5,6])
c= np.concatenate([a,b])

"""# Pandas

## 8. Create a dataframe with 3 rows and 2 columns
"""

import pandas as pd

data = [['stuart', 21],['vivek', 18],['arvindh', 16]]
df = pd.DataFrame(data, columns=['Name', 'Age'])
print(df )

"""## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023"""

pd.date_range(start='1/1/2023', end='02/10/2023')

"""## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]
"""

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

lists = [[1, 'aaa', 22],[2, 'bbb', 25],[3, 'ccc', 24]]

